### ISSUE TITLE
[Context-Tutor] Tutor needs replacing el-icon with e-icon in blue

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#100]
**Describe the idea**
Tutor (& PWA) needs replacing el-icon with e-icon in blue. 

**Screenshots**
![e-icon](https://user-images.githubusercontent.com/52330389/76316568-de9eb100-62eb-11ea-88bf-9ef237fe702f.png)

**Desktop:**
- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.132]

**Mobile:**
- Android
- Version [8.1.0]

**Comment by ErgerSusha** [comment]
Changed icons to new ones (6a6ee40).

**Comment by Vlad-CSA** [comment]
Done
