### ISSUE TITLE
[Context-Tutor] The back arrow disappeared in the filter. 

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#101]
**Describe the bug**
The back arrow disappeared in the filter on mobile (& PWA) and desktop. The place where the arrow should be is working.

**Screenshots**
![arrow disappeared](https://user-images.githubusercontent.com/52330389/76317486-53261f80-62ed-11ea-8bc8-b40140a55e80.png)

**Desktop:**
- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.132]

Mobile:
- Android
- Version [8.1.0]
- Browser [Chrome]

**Comment by Vlad-CSA** [comment]
Fixed
