### ISSUE TITLE
[Context-tutor][PWA] Text and buttons stick together on the mobile phone with the updated version of PWA

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#102]
**Describe the bug**
Text and buttons stick together with the dropped out keyboard on the mobile phone with the updated version of PWA.

**Screenshots**
with a dropped out keyboard - 
![update PWA](https://user-images.githubusercontent.com/52330389/76320422-bca82d00-62f1-11ea-9ed4-b485fbb2f551.png)
![update PWA1](https://user-images.githubusercontent.com/52330389/76320426-bdd95a00-62f1-11ea-9921-7c0ce23438c8.png)
without a dropped out keyboard -
![update PWA2](https://user-images.githubusercontent.com/52330389/76320428-bdd95a00-62f1-11ea-9985-384508cf4ec9.png)

**Smartphone:**
- Android
- Version [8.1.0]

**Comment by Vlad-CSA** [comment]
fixed
