### ISSUE TITLE
[Context-Tutor] The previous state is not displayed on the keyboard

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#105]
**Describe the bug**
When a user clicks the wrong letter, it is crossed out, but if he shifted focus to another word or empty space, and then again to the desired word, the previous state is not displayed on the keyboard.

**Screenshots**
![keyboard buggy](https://user-images.githubusercontent.com/52330389/76619114-33843680-653b-11ea-80ca-e6094b9e78e1.png)
![keyboard buggy2](https://user-images.githubusercontent.com/52330389/76619119-34b56380-653b-11ea-8ba7-54ccd50f02fe.png)

**Desktop:**
 - OS: [Windows 10 Pro]
 - Browser [Google Chrome]
 - Version [80.0.3987.132]

**Comment by sini4ka08** [comment]
Additional info: When a user clicks the wrong letter, it is crossed out, but if he clicks another wrong letter again, the previous state is not saved.
![keyboard buggy3](https://user-images.githubusercontent.com/52330389/76621102-b14a4100-653f-11ea-9786-a7a331586ece.png)

**Comment by ErgerSusha** [comment]
Added fix for this issue and pushed changes to both environments.

**Comment by Vlad-CSA** [comment]
Fixed...
