### ISSUE TITLE
APP/DES

### ISSUE THREAD

**Issue by marysergey** [easably/context-tutor#12]
![image](https://user-images.githubusercontent.com/47523695/52703282-0f000880-2f8f-11e9-9f1d-1a4bced3c183.png)

**1 block!!**

- [x] name it - My lessons

- [x] user can delete a lesson by scrolling

- [x] date adding lessons in the format on the right (look at the screen)

**2!!!**

- [x] save the setting of the first block

- [x] the missing letters are marked a dotted line

- [x] the user can try to pass the sentence again
in this case, when the user press the button -try again- the sentence opened again without filled words

**3!!!**
look at comments at screenshots
if you have questions write in skype

**Comment by marysergey** [comment]
### if you need a new special task please comment here

**Comment by marysergey** [comment]
https://github.com/easably/server-lessons/issues/5

**Comment by marysergey** [comment]
* the user can try to pass the sentence again
  in this case, when the user press the button -try again- the sentence opened again without filled words

**we refuse it**

**Comment by sergeifedorenko** [comment]
@marysergey I think we need to put design-UI like a png file to a folder (folder name Design) in the repository.
Sketch file we also need to put to the folder.
