### ISSUE TITLE
 There are no inscriptions on the diological windows

### ISSUE THREAD

**Issue by AlexeyYarmolchyk** [easably/context-tutor#124]
1.  Log in to the EasyLang application by clicking on the icon near the address bar.
2. Click on the Web Tutor link.
![Screenshot_20](https://user-images.githubusercontent.com/63914916/79755662-27517d00-8322-11ea-906e-6ec70cac1552.png)
3. In the section my lessons choose Flying Food.
![Screenshot_24](https://user-images.githubusercontent.com/63914916/79756041-b2327780-8322-11ea-9827-72ca64b1db75.png)
4. Perform the task for word arrangement, after completion, click "ok" in the window that appears.
5. Click on the [button] "Translate Sentence"
![Screenshot_25](https://user-images.githubusercontent.com/63914916/79756409-413f8f80-8323-11ea-98ed-c0a462543f8f.png)

**Comment by Vlad-CSA** [comment]
Fixed
