### ISSUE TITLE
Remove user icon 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#127]
When a user wants to sign in in tutor, user icon confuses him as if he has already gone to the page 
![83FF8362-06A4-435D-8421-32F630B1B884](https://user-images.githubusercontent.com/63041847/81539211-9c8bfd00-9378-11ea-8248-8b696c7ee399.jpeg)

@Vlad-CSA 

 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/81544997-ed075880-9380-11ea-9236-333bf97d9728.png)

![image](https://user-images.githubusercontent.com/58423687/81545199-322b8a80-9381-11ea-9376-65526bc79ad6.png)

**Comment by Vlad-CSA** [comment]
Confirm, i will implement it in nearest release
