### ISSUE TITLE
Identify user by his mail

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#130]
it’s difficult to understand if the user logged in to his own account 
It’s rather better to add his mail under the user icon
![76CD28CA-901A-4684-9C25-38D1577DF168](https://user-images.githubusercontent.com/63041847/81539983-aa8e4d80-9379-11ea-834f-8694d0d3ec93.jpeg)
@Vlad-CSA 
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/82539488-306a7f80-9b56-11ea-940e-f9ab013876b1.png)
