### ISSUE TITLE
[4h]correct listening. Add synthesized voice

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#144]
Description:
Only videos from TED have listening in the tutor:
![image](https://user-images.githubusercontent.com/63041847/85391393-c6793780-b552-11ea-9944-12160c993fcf.png)
Subtitle from video from youtube:
![image](https://user-images.githubusercontent.com/63041847/85391552-ffb1a780-b552-11ea-8703-85475b1aaf70.png)
Subtitle from local file:
![image](https://user-images.githubusercontent.com/63041847/85391656-2374ed80-b553-11ea-846a-d55cf41771bb.png)

You are to make synthesized voice for any type of content: from Browser, local file, Youtube, TED 

There is a bug: the subtitles have different duration of listening. Sometimes half the subtitle is played. Sometimes a different subtitle is caught:
only 3 words are played
![image](https://user-images.githubusercontent.com/63041847/84480265-f431c700-ac9c-11ea-886c-b89b9df6167e.png)
The next subtitle playes
![image](https://user-images.githubusercontent.com/63041847/84480486-4f63b980-ac9d-11ea-85a6-85ea282d1dcd.png)

**Comment by KatyaLogosh** [comment]
@Vlad-CSA Sentences still have different duration. Sometimes
subtitles capture other subtitles. Correct it

**Comment by Alexx-13** [comment]
1. Free but limited API - http://www.voicerss.org/

**Comment by Alexx-13** [comment]
2. Something similar to point 1 - https://responsivevoice.org/

**Comment by Alexx-13** [comment]
Good solution - <script src='https://code.responsivevoice.org/responsivevoice.js'></script> ; <input onclick="responsiveVoice.speak('This is the text you want to speak');" type='button' value='🔊 Play' />   
It was tooked from - https://stackoverflow.com/questions/15653145/using-google-text-to-speech-in-javascript

**Comment by Vlad-CSA** [comment]
[feat: include new audio method to games](https://github.com/easably/context-tutor/commit/bdc604c69ccc47bfe69119b52c7bea4089a8a255)
