### ISSUE TITLE
[6h]Add the design of feedback 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#157]
The necessary beautiful feedback, which will show everything, tell and will certainly praise 
Add it after  the user goes through all the sentences in the lesson
![image](https://user-images.githubusercontent.com/49349755/84637499-6e14bb00-aefe-11ea-8c77-b37a79bd2213.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=448%3A0

![image](https://user-images.githubusercontent.com/58423687/86000780-acd66500-ba16-11ea-9734-ec9e1f70e0a0.png)
