### ISSUE TITLE
[1.5h]New Tutor instruction will be needing translations 

### ISSUE THREAD

**Issue by AbeYelemessov** [easably/context-tutor#158]
![image](https://user-images.githubusercontent.com/60180904/84655703-197f3900-af1a-11ea-9ffb-4fa4b9fb5489.png)

Later on we will need all instructions to be translated into english at least.

**Comment by KatyaLogosh** [comment]
> ![image](https://user-images.githubusercontent.com/60180904/84655703-197f3900-af1a-11ea-9ffb-4fa4b9fb5489.png)
> 
> Later on we will need all instructions to be translated into english at least.

@bagorbenko
