### ISSUE TITLE
[3h maybe] Make brain in the instruction in the tutor in the first slide

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#169]
Create  a new sketch of drifting in thoughts brain in the first slide in the tutor 
![image](https://user-images.githubusercontent.com/63041847/85549101-4f15d780-b628-11ea-81fd-b70731c3ac58.png)

**Comment by annamaksimik** [comment]
https://easy4learn.com/instruction

![image](https://user-images.githubusercontent.com/58423687/85727244-873c1980-b6ff-11ea-9c5a-e7b35636ce90.png)
