### ISSUE TITLE
[3h]Make the text in the instruction in the tutor larger 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#172]
Make the text near the brain larger 
![image](https://user-images.githubusercontent.com/63041847/85847768-b5c5fd00-b7b0-11ea-9ae9-49151914cc45.png)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/86104923-59701f80-bac7-11ea-9d89-4d308860b28c.png)
