### ISSUE TITLE
[8h] Redesign hint buttons 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#173]
Description:
According to cust dev's users don't understand the hints, and can't notice them.
Expected behavior :
Users notice hints buttons if they are needed them. Users understand the meaning of the buttons 
screenshots:
![image](https://user-images.githubusercontent.com/63041847/85999018-35073b00-ba14-11ea-9ff0-8ee9981adbac.png)
![image](https://user-images.githubusercontent.com/63041847/85999325-9cbd8600-ba14-11ea-8697-edf792be3df9.png)
 There some examples from other word games:
![IMG_2614](https://user-images.githubusercontent.com/63041847/86008909-258eee80-ba22-11ea-9f41-8f9c2e102ab7.PNG)
there is an animation after you have finished the game
![image](https://user-images.githubusercontent.com/63041847/86008971-43f4ea00-ba22-11ea-81e7-39faee6c392b.png)
Lamp hint:
![image](https://user-images.githubusercontent.com/63041847/86009025-55d68d00-ba22-11ea-8284-938e1d50fc12.png)
Information about hints:
![image](https://user-images.githubusercontent.com/63041847/86009098-7272c500-ba22-11ea-9f14-e80c3eb8a3db.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=557%3A5722

![image](https://user-images.githubusercontent.com/58423687/87023174-12c5a800-c1e0-11ea-9e47-d6594542fb8d.png)
