### ISSUE TITLE
After tapping on the pause - the sentence starts for the beginning 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#174]
Description:
When a user wants to tap on pause- his sentence starts from the very beginning.
Pause implies "stop", not "replay".
Expected result:
The pause will work as vutton "stop"
![image](https://user-images.githubusercontent.com/63041847/86224849-12029580-bb92-11ea-9614-3c926afe4c3c.png)

**Comment by Vlad-CSA** [comment]
no need for pause function, instead i could change an icon when audio plays
