### ISSUE TITLE
[2h]add one slide instruction to the 3d game insctruction 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#176]
![image](https://user-images.githubusercontent.com/63041847/86240475-fb683880-bba9-11ea-9497-4cb7672cc019.png)
add " Расставь буквы в правильном порядке", "Put the letters in order"

**Comment by annamaksimik** [comment]
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=493%3A198

![image](https://user-images.githubusercontent.com/58423687/86245818-ba285680-bbb2-11ea-8ff2-7ee2d9bc1890.png)
