### ISSUE TITLE
[4h]redesign all one-slide insctructions 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#178]
Description:
After saving words from player- user go to tutor and one-slide instrucion displays. Users always don't remember the word that they have already saved.
You should redesign insctructions for all games : and make hint buttons availbale and clickable
![image](https://user-images.githubusercontent.com/63041847/86335324-07f69a80-bc57-11ea-9944-393f6202968e.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=493%3A198

![image](https://user-images.githubusercontent.com/58423687/86568439-89ab3880-bf75-11ea-8c76-5de50363b726.png)
