### ISSUE TITLE
[4h-5h]Make a menu with a list of games

### ISSUE THREAD

**Issue by bagorbenko** [easably/context-tutor#180]
now our games opens randomly. 
Make a menu with a list of games, providing their description:
Orthography(1st game)
Grammar(2nd game)
Spelling(3d game)

After tapping on one game

Examples in [48 issue UA](https://github.com/easably/UA/issues/48)

**Comment by KatyaLogosh** [comment]
Game list
Description:
When a user saves words from videos or articles- they are automatically saved to all games.
You are to make the list of games, which includes 5 different games:
The first game:"Insert the right letter"
The second game:"Restore the text"
The third game: "Build word"
The forth game: "Listen the sentence"
The fifth game: "Say the sentence/the word"
Note: After tapping on the forth and the fifth game appears the title : "coming soon"
Also you should write near the titles of the games- their level :
The first game: 2nd level
The second game:2nd level
The third game: 1 st level
The forth game: 2nd level
The fifth game: 3nd level
After tapping on the first three games- one slide instruction displays ( redesign, @annamaksimik remind you)
After watching the instruction- sentences display.
If a user saved more than 10 words- they will be displayed a little bit later, after user passes first 10 words.
@annamaksimik we have changed the name of the games

**Comment by annamaksimik** [comment]
**SKETCH WITHOUT DESIGN!!!**

https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=514%3A179

![image](https://user-images.githubusercontent.com/58423687/86584586-c84ced00-bf8d-11ea-9898-d19c452f3385.png)

**Comment by KatyaLogosh** [comment]
@annamaksimik can you make the design of this sketch?
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=532%3A4588
Can you add the background like in the lingualeo:
![image](https://user-images.githubusercontent.com/63041847/86793831-86e33d00-c074-11ea-9711-d5020a537941.png)
there is some pictures near the games, which explain the meaning of the games.

**Comment by annamaksimik** [comment]
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=561%3A758

![image](https://user-images.githubusercontent.com/58423687/87038331-3dbaf680-c1f6-11ea-9eb7-da17ed714106.png)
