### ISSUE TITLE
Create backround image for tutor games

### ISSUE THREAD

**Issue by bagorbenko** [easably/context-tutor#188]
Almost all web and mobile games have a backgroud image. 
Create backround image for tutor games.
**Examples:**
https://www.figma.com/file/UaUVavjZJmE6nnegi2gW3T/background?node-id=0%3A1

**Comment by annamaksimik** [comment]
**See variations for background Tutor**

https://www.figma.com/file/q4CeiybyaK3QEcsEKtzhpp/Tutor-Background?node-id=0%3A1


![image](https://user-images.githubusercontent.com/58423687/87926622-9dcd5a80-ca8a-11ea-95f7-8dd78de35695.png)
