### ISSUE TITLE
⏱Implement response to hover anc click games in the tutor game-list

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#191]
Description:
There is no any animation after tapping on the list of games. Make a simple animation after hover the cursor on the list of games.
Let users know that icons are clickable by indicating change of cursor 
![image](https://user-images.githubusercontent.com/63041847/87301263-eda2a380-c517-11ea-89a2-84b996ee544e.png)

**Comment by annamaksimik** [comment]
**Sketch** - https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=581%3A0
**Prototype** - https://www.figma.com/proto/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=581%3A0&viewport=-818%2C255%2C0.3851476013660431&scaling=min-zoom
![image](https://user-images.githubusercontent.com/58423687/87321911-7b40bc00-c535-11ea-815d-ff67e4b3118c.png)
