### ISSUE TITLE
[8h] Make sketches of new game in the tutor

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#201]
Description:
1. There will be a sentence with one missed word. (if there will be 2 or more missed words- they will be displayed in one sentence, like in the first game:
![image](https://user-images.githubusercontent.com/63041847/87930102-269ac500-ca90-11ea-837b-2a363542a7f4.png)
2. User can tap on any letter in the game- he will be always right with choice.
For example:
- What a wonderful ..... !
oldrw- User can tap on any letter in the word- it will be put in right place. 
3. There should be any  highlights, (progress bar) which demonstrates users staticstics 
The name of the game is " Put the letters in a right order"

**Comment by a-matyukh** [comment]
Prototype in [figma](https://www.figma.com/proto/p029prrhZr7pQVw1RFO1qV/201-Make-sketches-of-new-game-in-the-tutor?node-id=6%3A71&scaling=min-zoom).
Also made alternate sketch more simpler - [see in figma](https://www.figma.com/file/p029prrhZr7pQVw1RFO1qV/201-Make-sketches-of-new-game-in-the-tutor?node-id=12%3A10). It can be contain same logic as in first example.

**Comment by KatyaLogosh** [comment]
We decided to correct this game:
1. First of all you should do that user can make mistakes in this game
2. If a user made a mistake- the wrong letter is highlighted in red color
3. Use right order- not random order.

**Comment by KatyaLogosh** [comment]
Also you should change the top text in the game
![image](https://user-images.githubusercontent.com/63041847/88045838-d38c4500-cb57-11ea-8e1f-4e0cfa796221.png)

**Comment by a-matyukh** [comment]
Great prototype of great game is ready - [see in figma](https://www.figma.com/proto/p029prrhZr7pQVw1RFO1qV/201-Make-sketches-of-new-game-in-the-tutor?node-id=29%3A97&scaling=min-zoom)

**Comment by a-matyukh** [comment]
Prototype of mobile game with accepted mechanic: something gradually fall when user enter wrong letter - [see in figma](https://www.figma.com/proto/p029prrhZr7pQVw1RFO1qV/201-Make-sketches-of-new-game-in-the-tutor?node-id=29%3A1399&scaling=scale-down).

Happy case:
![happy](https://user-images.githubusercontent.com/20292939/88139800-1f42fb00-cbf9-11ea-8f3d-298254d12328.gif)

Sad case:
![sad](https://user-images.githubusercontent.com/20292939/88139836-3386f800-cbf9-11ea-9b04-c42f03b935f1.gif)

User can use help:
![help](https://user-images.githubusercontent.com/20292939/88139855-3c77c980-cbf9-11ea-8cb4-c69cf0940b8d.gif)
