### ISSUE TITLE
Draw 5 gamification versions

### ISSUE THREAD

**Issue by bagorbenko** [easably/context-tutor#206]
Draw 5 gamification versions with 4 states:
Neutral
Lose
Win (Finish)
Draw

**Video length is 10 seconds.**

![image](https://user-images.githubusercontent.com/66242439/88308444-b0a78f80-cd15-11ea-88c0-80e1c8750a2a.png)

**Comment by a-matyukh** [comment]
Started draft for future game mechanic specification - [see in figma](https://www.figma.com/file/FEy2jFMKHlz2qf4IcLD25B/206-Draw-5-gamification-versions?node-id=0%3A1)
Will be develop in process of making sketches.

**Comment by bagorbenko** [comment]
![image](https://user-images.githubusercontent.com/66242439/88367712-1b4be000-cd95-11ea-8405-961284245d3c.png)

**Comment by bagorbenko** [comment]
![image](https://user-images.githubusercontent.com/66242439/88387541-56f9a080-cdbb-11ea-8ba6-730a92031c4e.png)

**Comment by annamaksimik** [comment]
[video.zip](https://github.com/easably/context-tutor/files/4971796/video.zip)
![image](https://user-images.githubusercontent.com/58423687/88389179-9fff2400-cdbe-11ea-9328-8b67c329b799.png)

**Comment by a-matyukh** [comment]
Видео в архиве
[videos.zip](https://github.com/easably/context-tutor/files/4971842/videos.zip)

**Comment by a-matyukh** [comment]
reversed videos
[reversed-videos.zip](https://github.com/easably/context-tutor/files/4971949/reversed-videos.zip)

**Comment by annamaksimik** [comment]
**reversed videos**
[video.zip](https://github.com/easably/context-tutor/files/4972507/video.zip)
