### ISSUE TITLE
[2h] Make progress bar as hearts( if the user win-the quantuty of them is growing)

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#211]
Description:
makes progress in the form of a decreasing number of hearts with incorrect answers, and in case of a victory, a star appears. In addition, please single out the work with these hearts into a separate service method, so that the second Alexander could reuse it. And then there is a plan to change backgrounds (negative and positive) in order to visually show the current state of guessing for the user. At the end of the day, we can completely have a ready-made framework for template games and rivet already 4-5 just by changing the sprites of the hero and the background

**Comment by a-matyukh** [comment]
Progress added
https://github.com/easably/games/commit/ee73cb0d4cb4465bd64507193b1e0ce334558b1e
