### ISSUE TITLE
[12h]Implement new view of tutor

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#218]
- [x] Implement new design of preview games in the tutor
- [x] make new logic for open games

**Comment by annamaksimik** [comment]
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=687%3A321

![image](https://user-images.githubusercontent.com/58423687/91063411-a2ab9e00-e636-11ea-9860-4eda14deadc0.png)
