### ISSUE TITLE
Сreate UserFlow

### ISSUE THREAD

**Issue by marysergey** [easably/context-tutor#22]

**Comment by AnastasiyaFyodor** [comment]
<img width="871" alt="screen shot 2019-02-27 at 15 35 43" src="https://user-images.githubusercontent.com/47668201/53490669-5d3ffc00-3aa5-11e9-80fb-2dd6c429010f.png">
<img width="841" alt="screen shot 2019-02-27 at 15 30 43" src="https://user-images.githubusercontent.com/47668201/53490518-ee62a300-3aa4-11e9-8d37-964f172cb247.png">
<img width="492" alt="screen shot 2019-02-27 at 15 31 14" src="https://user-images.githubusercontent.com/47668201/53490519-ee62a300-3aa4-11e9-91c2-b40e28b8bd15.png">
