### ISSUE TITLE
[16h] Learn new 30 words using a tutor

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#223]
Description:
Learn 30 new words by next Friday using a tutor

**Comment by a-matyukh** [comment]
I made [trello-board](https://trello.com/b/TuV32TOR/elang-dogfoodinghttps://trello.com/b/TuV32TOR/elang-dogfooding) in that i described own expirience of learning words

**Comment by a-matyukh** [comment]
Also i made [trello-board](https://trello.com/b/o04DO6kc/%D0%B8%D0%B3%D1%80%D0%BE%D0%B2%D0%BE%D0%B9-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C) for conception of game vocabulary
