### ISSUE TITLE
Отсутствие полноценного словаря!

### ISSUE THREAD

**Issue by EugeneShastak** [easably/context-tutor#237]

**Comment by EugeneShastak** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/70751961/93061986-fbda8080-f67c-11ea-9e6e-34421745f238.jpg)
Отсутствие связи словаря из Player  в Tutor

**Comment by EugeneShastak** [comment]
![Screen_Shot_2020-09-02_at_15 00 56](https://user-images.githubusercontent.com/70751961/93062413-920ea680-f67d-11ea-9b3f-25e8f4a37053.png)
![Screenshot_1](https://user-images.githubusercontent.com/70751961/93062415-933fd380-f67d-11ea-8d9b-40bec55c248f.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/70751961/93062417-94710080-f67d-11ea-8649-610b7715b8de.jpg)

**Comment by EugeneShastak** [comment]
Скрины- предложения от Анны выше)

**Comment by sergeifedorenko** [comment]
@EugeneShastak @bagorbenko @annamaksimik 
1) Наверно надо My Vocabulary
2) 
![image](https://user-images.githubusercontent.com/5947223/93421654-9b388700-f8ba-11ea-86c0-493603d227d7.png)

-----
@EugeneShastak @KatyaLogosh  какое именно затруднение??

**Comment by EugeneShastak** [comment]
@sergeifedorenko Пользователю трудно обрабатывать уже добавленные слова
