### ISSUE TITLE
Add buttons and checkbox on page register

### ISSUE THREAD

**Issue by alexnpol** [easably/context-tutor#253]
Немного ввовдной информации.

У нас есть Тьютор. Тьютор - это страница с играми и словарем (https://easy4learn.com). Эти игры и словарь мы используем только для нашего расширения (у нас есть другие продукты, но они практически не связаны с Тьютором). Само понятие Тьютор это наше внутрикомандное понятие, на самой странице ты не увидишь этого слова. 

**Твоя задача сейчас поработать со страницей регистрации** https://easy4learn.com/register.:
1. Нужно добавить кнопки регистрации через гугл и фейсбук. Т.е. кликнув на копку гугла у пользователя появится окно выбора гугл аккаунта для входа и пользователь зарегистрируется в тьюторе через гугл. С фейсбуком логока такая же. Первый скрин - это куда добавить, второй - пример как может выглядеть. Ссылка на иконки гугл и фейсбука можно взять по ссылке: https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/eLang-Player-Desktop?node-id=1398%3A3198
К тому же, эти иконки уже есть на странице входа в аккаунт. Их нет только на странице регистрации.

2. Добавить чекбокс, нажав на который пользователь соглашается с нашими условиями. По умочанию галочка в чекбоксе не стоит. Ссылка на иконку чекбокса: https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/eLang-Player-Desktop?node-id=1398%3A3198

**Screenshots**
![image](https://user-images.githubusercontent.com/70699061/100213170-5d418a00-2f1f-11eb-8669-8a78eb58e181.png)
![image](https://user-images.githubusercontent.com/70699061/100214609-25d3dd00-2f21-11eb-8e19-112caca74044.png)

- [x]  Понятна ли данная задача? Поставь галочку если ДА.

**Comment by pavel232** [comment]
fixed in https://github.com/easably/context-tutor/pull/256
