### ISSUE TITLE
Fix a bug with the word area hover

### ISSUE THREAD

**Issue by alexnpol** [easably/context-tutor#254]
**Описание**:
На странице Мой словарь https://easy4learn.com/vocabulary при клике на слово ховер (подсветка этой области) немного съехала. Фича не совпадает с макетом.

**Решение**:
Пр клике на слово подвечивается вся область слова, ничего не съезжает. Сделать как в макете. Ссылка на макет: 
https://www.figma.com/file/78GiMuG6zyNqscyIR0Rk8K/Vocabulary?node-id=23%3A78
**Шаги воспроизведения:**
1. Открыть словарь в Тьюторе (до этого нужно создать свой аккаунт и добавить несколько слов в словарь)
2. Клтикнуть на область слова
3. Ошибка

**Ожидаемое поведение**
Во время клика на слово ховер не съезжает, работает как в макете.

**Скриншот**
как сейчас:
![image](https://user-images.githubusercontent.com/70699061/100219114-a9dc9380-2f26-11eb-9198-6a605556d260.png)
как должно быть:
![image](https://user-images.githubusercontent.com/70699061/100219772-76e6cf80-2f27-11eb-87d1-b06e2cea5526.png)

**Desktop (please replace the following information with your actual data):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by pavel232** [comment]
выполнено
