### ISSUE TITLE
Authorization via the Google button

### ISSUE THREAD

**Issue by alexnpol** [easably/context-tutor#260]
Description:
If a user once logged in to their account via Google, the next time they log in, the user will not see the window for selecting a Google account to log in to.
https://easy4learn.com/login

Solution:
Make sure that the user always has a choice of which account to log in to.

**Comment by pavel232** [comment]
выполнено
https://github.com/easably/context-tutor/pull/266

но нужно проверить работоспособность, так как аутентификации не работают на локал хосте
