### ISSUE TITLE
The window with the message that an invalid password was entered slid down

### ISSUE THREAD

**Issue by alexnpol** [easably/context-tutor#261]
**Describe the bug**
If you enter an incorrect password from the tutor's account, the user will receive a message about the wrong password, but not in the right place

**Expected behavior**
A text message about an incorrect password will appear in the center of the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/70699061/100663292-1f04fa00-3367-11eb-8a3a-0ea98309539c.png)

**Comment by pavel232** [comment]
done
https://github.com/easably/context-tutor/tree/fix-word-area-hover
