### ISSUE TITLE
The game page appears after changing the password

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/context-tutor#267]
**Steps to reproduce the behavior:**
1. sign up
2. click on store and add words to vocabulary 
3. click on your account
4. change password 

**Expected behavior**
Account page appears after changing password
**Actual result**
The game page appears after changing the password
**Screenshots**
![game](https://user-images.githubusercontent.com/75259195/101476821-5f640980-395f-11eb-9442-c44837c6ffdc.png)

**Comment by pavel232** [comment]
done
https://github.com/easably/context-tutor/pull/281
