### ISSUE TITLE
Blank screen opens when user try to play the game

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/context-tutor#268]
**Steps to reproduce the behavior:**
1. sign up
2. click on store and add words 
3. click on vocabulary 
4. chose some word and click on play
5. "play" modal window is opened
6. click on  "play"

**Expected behavior**
game is started
**Actual result** 
Blank screen opens
**Screenshots**
![addsomewords](https://user-images.githubusercontent.com/75259195/101483081-b28e8a00-3968-11eb-927a-73eee257d573.png)

**Comment by pavel232** [comment]
done

**Comment by MikeRogovskiy** [comment]
@alexnpol bug reproduced

**Comment by MikeRogovskiy** [comment]
@alexnpol 
when user adds words in store , user should get a pop-up window "Words from the set have been successfully added to your dictionary" and then open the dictionary and play some games
