### ISSUE TITLE
User is able to set the same password in "change password" flow

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/context-tutor#269]
**Steps to reproduce the behavior:**
1. sign up
2. click on change password 
3. edit "old password" and "new password" with the same data
4. change password 

**Expected behavior**
"The old and new passwords should be different" message appears
**Actual result**
1) Password is changed
2) Login page opens

**Screenshots**
After clicking on "change password" CTA  
![doblepass](https://user-images.githubusercontent.com/75259195/101485153-cd163280-396b-11eb-9d73-68b52ceec388.png)

**Comment by pavel232** [comment]
done
https://github.com/easably/context-tutor/pull/281
