### ISSUE TITLE
Black square appears in the right side of page

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/context-tutor#273]
**Steps to reproduce the behavior:**
1. sign up
2. use store and add words
3. click on vocabulary 
4. chose some word and start to play 
5. review the page

**Actual result**
Black square appears in the right side of page 

**Game**
- Drakosha Gosha is looking for potatoes
- RastaMasha in the kingdom of mushrooms

**Screenshots**
![notfull](https://user-images.githubusercontent.com/75259195/101608839-49198480-3a17-11eb-91d8-34a88d8e76cf.png)
![blck](https://user-images.githubusercontent.com/75259195/101608851-4c147500-3a17-11eb-98a4-07d92b68eb1d.png)
![black](https://user-images.githubusercontent.com/75259195/101608856-4dde3880-3a17-11eb-81b0-ff3fdf19bc3a.png)

**Comment by pavel232** [comment]
fixed in https://github.com/easably/context-tutor/pull/290
