### ISSUE TITLE
Error message appears when user tries to reset password

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/context-tutor#275]
**Steps to reproduce the behavior:**
1. click on "Forgot password?"
2. write valid email 
3. click on "Send email"

**Expected behavior**
Email about creating of new password is sent to the user's email
**Actual result**
Error massage "Toasts.email must be an email" appears 

_request https://easy4learn.com/forget failed with 400 error 
Response data:_
**_{statusCode: 400, message: ["email must be an email"], error: "Bad Request"}
error: "Bad Request"
message: ["email must be an email"]
statusCode: 400_**

**Screenshots**
![mail](https://user-images.githubusercontent.com/75259195/101615794-9994e000-3a1f-11eb-87b2-7c7c601a9d63.png)

**Comment by pavel232** [comment]
fixed
