### ISSUE TITLE
UI issues on the added word's pop-up modal

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/context-tutor#284]
**Steps to reproduce the behavior:**
1. open youtube.com 
2. click to add word in subtitle  
3. click on open in "My vocabulary"
4. https://2mymemory.com/vocabulary opens
5. open the added word

**Notes:** 
The same issue is actual for the words added from any sites like bbc.com

**Actual result**
UI issues on the word's pop-up modal

**Screenshots**
![Screenshot_4](https://user-images.githubusercontent.com/75259195/102222203-2c3bf000-3ef4-11eb-88a9-7f4dad41b249.png)
![Screenshot_5](https://user-images.githubusercontent.com/75259195/102222208-2cd48680-3ef4-11eb-9d29-6a8825db3423.png)

**Comment by pavel232** [comment]
fixed in https://github.com/easably/context-tutor/pull/288

**Comment by pavel232** [comment]
fix small word card window position in https://github.com/easably/context-tutor/pull/291
