### ISSUE TITLE
Change the email address for the support button

### ISSUE THREAD

**Issue by alexnpol** [easably/context-tutor#286]
fix is needed (should be support@easylang.app)
Replace text in letter **The language I use is {user lang}**

![Screenshot 2020-12-14 at 14 03 05](https://user-images.githubusercontent.com/61696166/102090240-21f6f480-3e15-11eb-8a05-6a2dc850176d.png)

![Screenshot 2020-12-14 at 14 02 44](https://user-images.githubusercontent.com/61696166/102090280-2f13e380-3e15-11eb-8c6b-4dbb54c06fff.png)

**Comment by pavel232** [comment]
changed in https://github.com/easably/context-tutor/pull/289

**Comment by MikeRogovskiy** [comment]
@alexnpol bug reproduced 
![Screenshot_23](https://user-images.githubusercontent.com/75259195/103650219-bbc34480-4f70-11eb-9ce6-4821501ca59c.png)

**Comment by pavel232** [comment]
changed https://github.com/easably/context-tutor/pull/296
