### ISSUE TITLE
Bug with link "Our terms" 

### ISSUE THREAD

**Issue by MikeRogovskiy** [easably/context-tutor#293]
**Steps to reproduce the behavior:**
1. open https://2mymemory.com/register
2. write e-mail/password/confirm password
3. click on link "Our terms"

**Actual result**
When the user clicks on the link he also sets the checkbox

**Comment by pavel232** [comment]
fixed https://github.com/easably/context-tutor/pull/295

**Comment by MikeRogovskiy** [comment]
@alexnpol bug reproduced

**Comment by pavel232** [comment]
забыл просто обновить дев, теперь все должно работать
