### ISSUE TITLE
Sign up form - Button captions

### ISSUE THREAD

**Issue by wilejczuk** [easably/context-tutor#37]
1. **Sign in** button should be **Sign up**
2. Footer text **Have already registered...** seems unclickable (and unclear). 
Should be: **Already registered? <a href to Sign in form>Sign in</a>**

![IMG_0656](https://user-images.githubusercontent.com/50916363/58471335-495f7100-814c-11e9-9124-bebb7a81c4e4.PNG)

**Comment by ErgerSusha** [comment]
Also closed by corrections of [720c0c0](https://github.com/easably/context-tutor/commit/720c0c0c7de646cc15fcdd06015c9cae1fa47a28)
