### ISSUE TITLE
Sign up form - Pop up window

### ISSUE THREAD

**Issue by wilejczuk** [easably/context-tutor#39]
- If credentials are correct, the message should be:

<s>Error</s>
sergeifedorenko@taqtile.com is already registered
<a href=homepage while signed in>Proceed to application</a>

- If credentials are wrong, the message should be:

<s>Error</s>
sergeifedorenko@taqtile.com is already registered
<a href=sign in form>Sign in</a>

![IMG_2963](https://user-images.githubusercontent.com/50916363/58473451-4dda5880-8151-11e9-9b78-7b9ae9188708.PNG)

**Comment by ErgerSusha** [comment]
Sign in and Sign up forms are currently represented by single Sign in / up form, that's why described behavior is not up-to-date anymore. Closing issue for now.
