### ISSUE TITLE
Improvement - swipe left/right

### ISSUE THREAD

**Issue by alla-cherniauskaya** [easably/context-tutor#43]
When I'm in this window, I intuitively want to _swipe_ left and write, rather than tapping small headings below.

![image](https://user-images.githubusercontent.com/47523071/58638135-b9145e00-82fc-11e9-8482-4d42ab79e8a4.png)

**Comment by ErgerSusha** [comment]
Implemented this functionality for all plarforms by commits ba52f65, a6aee70, 10c9cb6.
