### ISSUE TITLE
Sign in form - Remember password & Auto filling options

### ISSUE THREAD

**Issue by wilejczuk** [easably/context-tutor#44]
Add **Remember password** and **Auto filling** options to the Sign in form.
(If the user filled username and password forms, but didn't confirm, then switched to another browser tab and back - filled username and password disappear.

**Desktop (please replace the following information with your actual data):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by ErgerSusha** [comment]
Added email and password autocomplete options to tags in fdb27b4. Tested on iOS Safari and Chrome on macOS. Closing issue for now.
