### ISSUE TITLE
Missing statistics/Answer result

### ISSUE THREAD

**Issue by marysergey** [easably/context-tutor#5]
Missing answer result.
The result should be opposite the lesson and match the color depending on the answer.

**Comment by marysergey** [comment]
![image](https://user-images.githubusercontent.com/47523695/52793178-2e299380-307e-11e9-88ba-6767148d81e5.png)

the user wants to see the correct filtering by selecting the desired group
that is exactly
Red color stats give up

Red and yellow give up and use a hint

Please do it soon.

**Comment by ErgerSusha** [comment]
Statistics displayment was implemented in numerous previous commits.
