### ISSUE TITLE
Position of existing sentences number

### ISSUE THREAD

**Issue by alla-cherniauskaya** [easably/context-tutor#54]
The number that is right next to the time you last edit lesson looks like refer to that time, but not to the number of sentences.

Related to: #50 

![image](https://user-images.githubusercontent.com/47523071/64178081-73ba7c00-ce69-11e9-9ae6-817599c57e0a.png)

**Suggestion**: Put the number of sentences next to the lesson Title

**Comment by ErgerSusha** [comment]
Design for sentences number displaying is currently different. Closing issue for now.
