### ISSUE TITLE
[Context-Tutor] End of lesson not displayed for user

### ISSUE THREAD

**Issue by NadiaZu** [easably/context-tutor#68]
**Describe the bug**
When a user trains the last sentence in a lesson, it is not displayed that this is the last sentence.

**Expected behavior**
When the user trains the last sentence in the lesson, the "Next Sentence" button should not be displayed in statistics.

**Screenshots**
![image](https://user-images.githubusercontent.com/55742055/71158144-742e2580-2254-11ea-9c65-ca44067e3d80.png)

**Desktop:**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by sini4ka08** [comment]
Bug is fixed. It doesn't repeat.
