### ISSUE TITLE
[Context-Tutor] Two words are written with a hyphen have not been fully written or opened by the user

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#78]
**Describe the bug**
When a user trains the sentence where are two words are written with a hyphen, after first word a displayed statistics appears like this
![word with hyphen](https://user-images.githubusercontent.com/52330389/74732610-ab708100-525b-11ea-98af-db328b96c9a7.png)

The next time this sentence opened like this
![word with hyphen2](https://user-images.githubusercontent.com/52330389/74732627-b88d7000-525b-11ea-84be-eb9498287d68.png)

**Expected behavior**
When the user trains the sentence where are words are written with a hyphen, the user can trains all sentence.

**Additional info:**
But if the user trains the sentence where are three words are written with a hyphen or words are written with a dash, this sentence is working correctly. 
![word with hyphen4](https://user-images.githubusercontent.com/52330389/74732687-db1f8900-525b-11ea-999c-960a2e47787e.png)

![word with hyphen3](https://user-images.githubusercontent.com/52330389/74732681-d6f36b80-525b-11ea-9228-ce1a509557f1.png)

**Desktop:**

- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.106]

**Mobile:**

- Android  
- Version [8.1.0]

**Comment by ErgerSusha** [comment]
Pushed fixes to development environment.

**Comment by sini4ka08** [comment]
Bug is fixed. It doesn't repeat.
