### ISSUE TITLE
[Context-tutor] Filter doesn't have a return button

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#79]
**Describe the bug**
The user went into the filter, and there is no return button.

**Expected behavior**
Filter have a return button.

**Screenshots**
![Filter](https://user-images.githubusercontent.com/52330389/74822654-8725aa80-5316-11ea-87c0-f105f2397554.png)

**Desktop:**

- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.106]

**Mobile:**
 
- Android
- Version [8.1.0]

**Comment by ErgerSusha** [comment]
Current UI sketches contained no back button. Please, confirm, if they need to be corrected.

**Comment by sini4ka08** [comment]
User can't exit the filter. The filter needs a return arrow.
![Filter with arrow](https://user-images.githubusercontent.com/52330389/74943478-7e5fd200-5405-11ea-93b1-a363c84f94d9.png)

**Comment by ErgerSusha** [comment]
> User can't exit the filter. The filter needs a return arrow.
> ![Filter with arrow](https://user-images.githubusercontent.com/52330389/74943478-7e5fd200-5405-11ea-93b1-a363c84f94d9.png)

Added filters back button in #809a7c4. Pushed to [development environment](https://2mymemory.com).

**Comment by Vlad-CSA** [comment]
I think such things can not be attributed to bugs. These are problems with UI / UX. And developer made functionality according to the sketch. But this behavior also worry me when the back button is missing or the changes made cannot be applied.

**Comment by sini4ka08** [comment]
The filter has a return button.
