### ISSUE TITLE
[Context-Tutor] The link "Write to developers" doesn't work.

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#80]
**Describe the bug**
The link "Write to developers" doesn't work.

**Screenshots**
![Write to developers](https://user-images.githubusercontent.com/52330389/74823190-601ba880-5317-11ea-8e40-24c5cd6551c5.png)

**Desktop:**

- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.106]

**Comment by ErgerSusha** [comment]
Current implementation uses mailto protocol to send info to developers. Windows is the only platform, that does not set default mailto receiver. This can be corrected by setting default is Windows Settings.

**Comment by Vlad-CSA** [comment]
![mail-to-dev](https://user-images.githubusercontent.com/49349755/75089487-52119600-556a-11ea-81ba-277d12729ba7.png)
Agree with **ErgerSusha**, it's absolutely normal behavior on windows. And if you have setup default client for mail like Microsoft Outlook the button will work. First part of screenshot shows that when you hover over the button, the "mailto" link appears(bottom left of the screen), and the second part of screen shows that the default client is called on windows, everything works as it should.

**Comment by sini4ka08** [comment]
If everything works correctly, I close issue.
