### ISSUE TITLE
[Context-tutor] [PWA] Tutor icon looks buggy/dirty

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#85]
**Screenshots**
![icon](https://user-images.githubusercontent.com/52330389/75424315-734ef980-5951-11ea-92c6-7ee19fdb4c08.png)
![icon2](https://user-images.githubusercontent.com/52330389/75424317-74802680-5951-11ea-8153-451c453bbc73.png)
![icon3](https://user-images.githubusercontent.com/52330389/75424319-74802680-5951-11ea-9cc7-796b26a6b2ad.png)

**Expected behavior**
Is it possible to remove a dark strip on the icon? She doesn't look like a shadow. It looks like a glitch.

**Smartphone:**

- Device: [Meizu Redmi 6]
- OS: [Android 8.1.0]
- Browser [Chrome & Mi Browser]

**Comment by sergeifedorenko** [comment]
@annamaksimik check it please
