### ISSUE TITLE
[Context-tutor] [PWA] Lessons are not updated yet

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#87]
**Describe the bug**
How should lessons be updated? 
When a user installed the tutor on the desktop of his mobile. The tutor has old lessons.
I can’t check for changes to the lessons.

**Screenshots**
My lessons now -
![update through QR4](https://user-images.githubusercontent.com/52330389/75433421-f88dda80-5960-11ea-99f0-7dd19bfcdab7.png)
My lessons on the desktop of a mobile.
![update through QR5](https://user-images.githubusercontent.com/52330389/75433425-f9bf0780-5960-11ea-8823-b966ce123eca.png)

**Smartphone:**
- Device: [Meizu Redmi 6]
- OS: [Android 8.1.0]
- Browser [Chrome & Mi Browser]

**Comment by ErgerSusha** [comment]
PWA is currently running on development domain only, but the upper image contains lessons from production domain, that's why PWA contains lessons from https://2mymemory.com.
