### ISSUE TITLE
[Context-tutor] [PWA] Tutor ceased to offer to be added to the main screen

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#92]
**Describe the bug**
Tutor isn't on the main screen.
And when a user is in tutor in browser, tutor doesn't offer to add him to the main screen.

**Smartphone:**
- Device: [Meizu Redmi 6]
- OS: [Android 8.1.0]
- Browser [Chrome & Mi Browser]

**Comment by ErgerSusha** [comment]
Seems like a default mobile browsers behavior in PWA environments. Offer to PWA installation shows only first time, but can be manually triggered by page cache cleaning. Closing issue for now.
