### ISSUE TITLE
[Context-tutor] User can't delete account in English version of Tutor

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#95]
**Describe the bug**
When the user clicks [delete account] in English version of Tutor, a window appears as in the picture
![Delete account in English](https://user-images.githubusercontent.com/52330389/75524249-97c4d780-5a1e-11ea-91f2-b6f3b355bf70.png)

**Additional info:**
User can delete account in Russian version of Tutor
![Delete account in English2](https://user-images.githubusercontent.com/52330389/75524252-98f60480-5a1e-11ea-864a-15b539979c05.png)

**Desktop:**
OS: [Windows 8]
Browser [Google Chrome]
Version [80.0.3987.106]

**Smartphone:**
Device: [Meizu Redmi 6]
OS: [Android 8.1.0]
Browser [Chrome]

**Comment by ErgerSusha** [comment]
Must have been fixed by the above mentioned commit. Pushed changes to [development environment](https://2mymemory.com).

**Comment by sini4ka08** [comment]
Bug is fixed.
