### ISSUE TITLE
[Context-tutor] "Need help?" block is shifted to the left

### ISSUE THREAD

**Issue by sini4ka08** [easably/context-tutor#96]
**Describe the bug**
"Need help?" block is not in the middle of a sentence.

**Screenshots**
![Need help frame](https://user-images.githubusercontent.com/52330389/75525885-ba0c2480-5a21-11ea-914a-b3ac20d2707f.png)

**Desktop:**
- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.106]

**Comment by ErgerSusha** [comment]
Current UI sketches contained helper block aligned to the left. Please, confirm, if it is to be corrected.

**Comment by sini4ka08** [comment]
Not relevant design now.
